<a href="https://colab.research.google.com/github/mirsazzathossain/CSE317-Lab/blob/autumn_2022/Lab_Assignment_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### **Wheat Seed Classification**

In this assignment, you will use the [Wheat Seed Dataset](https://archive.ics.uci.edu/ml/datasets/seeds) to classify the type of wheat seed based on the measurements of the seed. The dataset contains 7 attributes and 210 instances. The attributes are:

1. Area
2. Perimeter
3. Compactness
4. Length of Kernel
5. Width of Kernel
6. Asymmetry Coefficient
7. Length of Kernel Groove

Based on the attributes, the dataset contains 3 classes:

1. Kama
2. Rosa
3. Canadian

The text file `seeds_dataset.txt` contains the dataset. The first 7 columns are the attributes and the last column is the class label. The class labels are encoded as  1, 2, and 3 for Kama, Rosa, and Canadian, respectively. The goal of this assignment is to build a classifier that can predict the type of wheat seed based on the measurements of the seed. Follow the instructions below to complete the assignment.

#### **Instructions**

1. Download the dataset from [Github](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/mirsazzathossain/CSE317-Lab-Numerical-Methods/blob/main/datasets/seeds_dataset.txt). It should be saved as `seeds_dataset.txt`.
2. Upload the dataset to your Google Drive and mount your Google Drive to Colab.
3. Read the dataset using numpy's built-in function `np.genfromtxt()`. Pass the following parameters to the function:
    - `fname`: The path to the dataset
    - `delimiter`: The delimiter used in the dataset to separate the attributes (Hint: Use `'\t'` as the delimiter)
    
4. Shuffle the dataset using `np.random.shuffle()`. Pass the following parameters to the function:
    - `x`: The dataset
5. Split the dataset into features and labels. The first 7 columns of the dataset are the features and the last column is the label. Use numpy's array slicing to split the dataset into features and labels. (Hint: Use `:` to select all the rows and `0:7` to select the first 7 columns for features and `7` to select the last column for labels)
6. Split the dataset into training and testing sets. Use numpy's built-in function `np.split()` to split the dataset into training and testing sets. Pass the following parameters to the function:
    - `ary`: The dataset
    - `indices_or_sections`: The number of instances in the training set (Hint: Use `int(0.8 * len(dataset))` to get the number of instances in the training set)
    - `axis`: The axis to split the dataset (Hint: Use `0` to split the dataset along the rows)
7. Find the minimum and maximum values of each feature in the training set. Use numpy's built-in function `np.min()` and `np.max()` to find the minimum and maximum values of each feature in the training set. Pass the following parameters to the function:
    - `a`: The training set
    - `axis`: The axis to find the minimum and maximum values (Hint: Use `0` to find the minimum and maximum values along the columns)
8. In this step, you must normalize the training and test sets. Nomalization is an essential part of every machine learning project. It is used to bring all the features to the same scale. If the features are not normalized, the higher-valued features will outnumber the lower-valued ones.

    For example, suppose we have a dataset with two features: the number of bedrooms in a house and the size of the garden in square feet and we are trying to forecast the rent of the residence. If the features are not normalized, the feature with higher values will take precedence over the feature with lower values. In this scenario, the garden area has a greater value. As a result, the model will make an attempt to forecast the house's price depending on the size of the garden. As a consequence, the model will be faulty since most individuals will not pay higher rent for more garden area. We need to normalize the features in order to prevent this. Let's look at the following illustration to better comprehend what we have said:
    
    - House 1: 2 bedrooms, 2500 sq. ft. garden
    - House 2: 3 bedrooms, 500 sq. ft. garden
    - House 3: 7 bedrooms, 2300 sq. ft. garden

    Considering that most people won't pay more for a larger garden, it follows that the rent for House 1 should be more comparable to House 2 than to House 3. However, if we give the aforementioned data to a k-NN classifier without normalization, it will compute the euclidean distance between the test and training examples and pick the class of the test instance based on the class of the closest training instance.

    The euclidean distance between the test instance and the training instances will be:

    - Distance between house 1 and house 2: $\sqrt{(2-3)^2 + (2500-500)^2} = 2000$
    - Distance between house 1 and house 3: $\sqrt{(2-7)^2 + (2500-2300)^2} = 200$

    As you can see, the distance between houses 1 and 3 is shorter than that between houses 1 and 2. As a result, the model will forecast that house 1 will cost around the same as house 3. This is not what was anticipated. We need to normalize the features in order to prevent this. To normalize the features, subtract the minimum value of each feature from all the values of that feature and divide the result by the range of the feature. The range of a feature is the difference between the maximum and minimum values of that feature. The formula for normalization is given below:

    $$x_{normalized} = \frac{x - min(x)}{max(x) - min(x)}$$

    where $x$ is the feature vector. The above formula will normalize the features to a scale of 0 to 1.

    Let's normalize the features in the above example. To do so, we need to find the minimum and maximum values of each feature. The minimum and maximum values of the number of bedrooms are 2 and 7, respectively. The minimum and maximum values of the garden area are 500 and 2500, respectively. The normalized values of the features are given below:

    - House 1: $(2 - 2) / 5 = 0$ bedrooms, $(2500 - 500) / 2000 = 0.75$ sq. ft. garden
    - House 2: $(3 - 2) / 5 = 0.2$ bedrooms, $(500 - 500) / 2000 = 0$ sq. ft. garden
    - House 3: $(7 - 2) / 5 = 1$ bedrooms, $(2300 - 500) / 2000 = 0.85$ sq. ft. garden

    Now, the euclidean distance between the test instance and the training instances will be:

    - Distance between house 1 and house 2: $\sqrt{(0-0.2)^2 + (0.75-0)^2} = 0.77$
    - Distance between house 1 and house 3: $\sqrt{(0-1)^2 + (0.75-0.9)^2} = 1.11$

    As you can see now, the distance between houses 1 and 2 is shorter than that between houses 1 and 3. The model will thus forecast that house 1 will cost about the same as house 2, according to the prediction. This is what is anticipated. This is what normalization does. It equalizes the scale of all features. This is important because it prevents the features with higher values from dominating the features with lower values.

    Use the minimum and maximum values you found in the previous step to normalize the training and test sets.
9. Now, you have to build a classifier to classify the type of wheat seed based on the measurements of the seed. Use the K-Nearest Neighbors algorithm to build the classifier. Use the Euclidean distance to find the nearest neighbors.

10. Output the number of data points in the testing set and the number of correct predictions made by the classifier for each class.

In [1]:
import os
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier

#from google.colab import drive
#drive.mount('/content/drive')
#3 path & get data
fname = "seeds_dataset.txt"
delimiter = '\t'
x = np.genfromtxt(fname, delimiter=delimiter)

#4 shufflin
np.random.shuffle(x)

#5 split 
features = x[:, 0:7]
labels = x[:, 7]


#6 
train_features, test_features = np.split(features, [int(0.8*len(x))])
train_labels, test_labels = np.split(labels, [int(0.8*len(x))])

#axis
min_values = np.min(train_features, axis=0)
max_values = np.max(train_features, axis=0)

#7
for i in range(7):
    print(f"Feature {i + 1}: Min={min_values[i]}, Max={max_values[i]}")

#8
normalized_train_features = (train_features - min_values) / (max_values - min_values)

normalized_test_features = (test_features - min_values) / (max_values - min_values)

print("Normalized Training Features:")
print(normalized_train_features)

print("\nNormalized Test Features:")
print(normalized_test_features)

Feature 1: Min=10.59, Max=20.97
Feature 2: Min=12.41, Max=17.25
Feature 3: Min=0.8081, Max=0.9183
Feature 4: Min=4.899, Max=6.666
Feature 5: Min=2.63, Max=3.991
Feature 6: Min=0.7651, Max=8.456
Feature 7: Min=4.519, Max=6.453
Normalized Training Features:
[[0.238921   0.31198347 0.36206897 ... 0.2674504  0.590165   0.45294726]
 [0.36512524 0.37190083 0.78947368 ... 0.50110213 0.22063738 0.22595657]
 [0.47880539 0.51239669 0.67332123 ... 0.5716385  0.5469971  0.68665977]
 ...
 [0.36127168 0.40495868 0.58529946 ... 0.41146216 0.07124004 0.3262668 ]
 [0.91618497 0.94628099 0.60344828 ... 0.84864071 0.15471531 0.99793175]
 [0.30346821 0.33884298 0.60163339 ... 0.35562087 0.28174856 0.1582213 ]]

Normalized Test Features:
[[6.16570328e-02 4.54545455e-02 6.88747731e-01 1.69779287e-03
  1.82953711e-01 1.95542784e-01 9.51396070e-02]
 [5.32755299e-01 5.35123967e-01 8.33938294e-01 4.58404075e-01
  6.28214548e-01 1.95672808e-01 4.77766287e-01]
 [8.04431599e-01 8.42975207e-01 6.07078040e-01 8.7492

In [2]:

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
import matplotlib.pyplot as plt


classifier = KNeighborsClassifier(n_neighbors=3) 
classifier.fit(normalized_train_features, train_labels)


predictions = classifier.predict(normalized_test_features)


accuracy = round(accuracy_score(test_labels, predictions), 3)
conf_matrix = confusion_matrix(test_labels, predictions)

print(f"Accuracy: {accuracy}")
print("Confusion Matrix:")
print(conf_matrix)


for i in range(10):
    print(f"Actual: {test_labels[i]}, Predicted: {predictions[i]}")


Accuracy: 0.976
Confusion Matrix:
[[12  0  0]
 [ 1 18  0]
 [ 0  0 11]]
Actual: 1.0, Predicted: 1.0
Actual: 1.0, Predicted: 1.0
Actual: 2.0, Predicted: 2.0
Actual: 3.0, Predicted: 3.0
Actual: 2.0, Predicted: 2.0
Actual: 3.0, Predicted: 3.0
Actual: 2.0, Predicted: 2.0
Actual: 1.0, Predicted: 1.0
Actual: 2.0, Predicted: 2.0
Actual: 3.0, Predicted: 3.0


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
